### ISSUE TITLE
Failed to activate the autocomplete-paths package

### ISSUE THREAD

**Issue by klb-rodriguez** [atom/settings-view#430]
After Update atom to 0.187.0 and update packages

**Atom Version**: 0.187.0
**System**: linux 3.16-3-amd64
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.184.0

### Stack Trace

Failed to activate the autocomplete-paths package

```
At undefined is not a function

TypeError: undefined is not a function
  at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:355:117)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:243:16)
  at /usr/share/atom/resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:465:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "espresso-soda"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.11.0
autocomplete-paths, v1.0.2
autocomplete-plus, v0.22.1
bootstrap3-snippets, v0.1.1
color-picker, v1.4.4
espresso-soda, v0.5.0
file-icons, v1.5.1
php-twig, v3.0.0
save-session, v0.11.5
symfony-snippets, v0.3.0
terminal-status, v1.3.5

# Dev
No dev packages
```

**Comment by izuzak** [comment]
This should show up only after you update some packages. If you restart Atom after that everything should be fine. We're tracking this problem over in https://github.com/atom/settings-view/issues/416 so I'm going to close this. Thanks for the report, though!

**Comment by klb-rodriguez** [comment]
Ok, thanks for the info.
